ORC-1373: Provide directional exceptions instead of NPE in case of `DynamicByteArray` length overflow
### What changes were proposed in this pull request?

When `DynamicByteArray` calculates `chunkIndex` overflow, it will throw NPE.
We can throw exception to remind users to avoid this problem by configuring what ORC parameters.

### Why are the changes needed?

When the written string is very large, the grow calculation may overflow, causing the array data not to be expanded, and then NPE.

org.apache.orc.impl.DynamicByteArray#add(byte[], int, int)
```java
grow((length + valueLength) / chunkSize);
```

#### Log

```java
Caused by: java.lang.NullPointerException
	at java.lang.System.arraycopy(Native Method)
	at org.apache.orc.impl.DynamicByteArray.add(DynamicByteArray.java:115)
	at org.apache.orc.impl.StringRedBlackTree.addNewKey(StringRedBlackTree.java:48)
	at org.apache.orc.impl.StringRedBlackTree.add(StringRedBlackTree.java:60)
	at org.apache.orc.impl.writer.StringTreeWriter.writeBatch(StringTreeWriter.java:69)
	at org.apache.orc.impl.writer.StructTreeWriter.writeRootBatch(StructTreeWriter.java:56)
	at org.apache.orc.impl.WriterImpl.addRowBatch(WriterImpl.java:696)
```

### How was this patch tested?

#### Local Test
org.apache.orc.impl.TestDynamicArray#testBigByteArray
```java
 Test
  public void testBigByteArray() {
    DynamicByteArray dba = new DynamicByteArray(128, 32 * 1024);

    byte[] val = new byte[1024];
    dba.add(val, 0, val.length);

    byte[] bigVal = new byte[Integer.MAX_VALUE - 16];
    dba.add(bigVal, 0, bigVal.length);
  }
```

#### Output

```java
java.lang.RuntimeException: chunkIndex overflow:-65535. You can set orc.column.encoding.direct=columnName, or orc.dictionary.key.threshold=0 to turn off dictionary encoding.
	at org.apache.orc.impl.DynamicByteArray.grow(DynamicByteArray.java:73)
	at org.apache.orc.impl.DynamicByteArray.add(DynamicByteArray.java:122)
	at org.apache.orc.impl.TestDynamicArray.testBigByteArray(TestDynamicArray.java:36)
```

Closes #1412 from cxzl25/ORC-1373.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>