ORC-1587: Fix usage command of SparkBenchmark document
### What changes were proposed in this pull request?
```
java -jar spark/target/orc-benchmarks-spark-${ORC_VERSION}.jar spark data
```

### Why are the changes needed?
```bash
java -jar spark/target/orc-benchmarks-spark-*.jar spark data
```

```
Error: Invalid or corrupt jarfile spark/target/orc-benchmarks-spark-2.1.0-SNAPSHOT-nohive.jar
```

### How was this patch tested?
local test

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #1749 from cxzl25/ORC-1587.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit 850072d438a46c7621de03ea7e4a194c128fc5e8)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>