ORC-851: Fix CNFE in ORC tools uber jar (#753)
### What changes were proposed in this pull request?
This PR aims to fix CNFE in ORC tools uber jar.

### Why are the changes needed?
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/conf/Configuration
	at org.apache.orc.tools.Driver.main(Driver.java:101)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.conf.Configuration
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 1 more
```
### How was this patch tested?
Manual.

(cherry picked from commit 657330a7a1bb3e87c3020fab057fefd03fe97228)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>