ORC-879: Fix testDateTimeTypeSupport unit test (#942)
### What changes were proposed in this pull request?

```java
OffsetDateTime datetime4 = OffsetDateTime.of(datetime2, ZoneOffset.ofHours(-7));
datetime4.toString().replace("07:00", "0700")
```
The intention here is to replace the format of the time zone, but it is possible to replace HH:mm.

https://github.com/apache/orc/pull/941#issuecomment-946774472
```
java.time.format.DateTimeParseException: Text '2021-10-19T0700:01.683210-0700' could not be parsed at index 13
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
	at java.base/java.time.format.DateTimeFormatter.parseBest(DateTimeFormatter.java:1994)
	at org.apache.orc.tools.convert.JsonReader$TimestampColumnConverter.convert(JsonReader.java:169)
	at org.apache.orc.tools.convert.JsonReader.nextBatch(JsonReader.java:375)
	at org.apache.orc.tools.convert.TestJsonReader.testDateTimeTypeSupport(TestJsonReader.java:132)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at
```

This pr is aimed at fixing this bug.

### Why are the changes needed?

Ensure that UT behave consistently at all times.

### How was this patch tested?

Using the current UT.

(cherry picked from commit f54833e5816f222c490e473fd9cb51fefc0e3371)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>