ORC-919: Spark bench objenesis should be the same as Spark (#830)
### What changes were proposed in this pull request?
This PR aims to use the same objenesis version as Spark in Spark benchmark.

### Why are the changes needed?

To fix the class not defined error seen below

```
java.lang.NoClassDefFoundError: org/objenesis/strategy/InstantiatorStrategy
	at org.apache.orc.mapred.OrcInputFormat.setSearchArgument(OrcInputFormat.java:97)
	at org.apache.orc.mapreduce.OrcInputFormat.setSearchArgument(OrcInputFormat.java:57)
	at org.apache.spark.sql.execution.datasources.orc.OrcFileFormat.$anonfun$buildReaderWithPartitionValues$5(OrcFileFormat.scala:190)
```

### How was this patch tested?

Manual.

```
java -jar spark/target/orc-benchmarks-spark-1.8.0-SNAPSHOT.jar spark data -d sales -c snappy -f orc
```

(cherry picked from commit a5b1181609ec0e1508b7d9afea6166c1c73637ff)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>