ORC-945: Add OUTPUT_QUIET, ERROR_QUIET to suppress Java8 addopen error messages (#858)
### What changes were proposed in this pull request?
This PR aims to add `OUTPUT_QUIET` and `ERROR_QUIET` to suppress Java8 `add-open` error messages

### Why are the changes needed?
Error messages could be misleading, so we had better suppress it. 
- https://github.com/apache/orc/runs/3324055264
```
Unrecognized option: --add-opens
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### How was this patch tested?
Check the GHA logs on this PR.