ORC-658: Fix NoClassDefFoundError during benchmark data generation (#535)
### What changes were proposed in this pull request?

This PR aims to add `hadoop-hdfs` dependency to `bench/core` module.

### Why are the changes needed?

This will fix `NoClassDefFoundError` error during data generation.
```
$ java -jar core/target/orc-benchmarks-core-*-uber.jar generate data
[WARN ] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/client/HdfsDataOutputStream$SyncFlag
```

### How was this patch tested?

```
cd java/bench
mvn package
./fetch-data.sh
java -jar core/target/orc-benchmarks-core-*-uber.jar generate data
```

(cherry picked from commit 84353fbfc447b06e0924024a8e03c1aaebd3e7a5)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>