ORC-1449: Add `-Wno-unused-macros` for Clang 14.0
### What changes were proposed in this pull request?

This PR aims to ignore `unused-macro` warning in Clang 14.0.

### Why are the changes needed?

This is required to test on the latest Mac.

**Environment**
```
$ g++ --version
Apple clang version 14.0.0 (clang-1400.0.28.1)
...
```

**BEFORE**
```
$ make package test-out
...
/Users/dongjoon/APACHE/orc-merge/c++/src/CpuInfoUtil.cc:65:9: error: macro is not used [-Werror,-Wunused-macros]
#define UNUSED(x) (void)(x)
        ^
1 error generated.
make[2]: *** [c++/src/CMakeFiles/orc.dir/CpuInfoUtil.cc.o] Error 1
make[1]: *** [c++/src/CMakeFiles/orc.dir/all] Error 2
make: *** [all] Error 2
```

**AFTER**
```
make package test-out
...
100% tests passed, 0 tests failed out of 8

Total Test time (real) = 156.15 sec
Built target test-out
```

### How was this patch tested?

Pass the CIs and manual tests on Clang 14.0.

Closes #1544 from dongjoon-hyun/ORC-1449.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit d7d21720ae8888e2d13e0e93365bcf9393ca5f9c)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>