ORC-1973: [C++] Use `int64_t` instead of `google::protobuf::int64` for `Protobuf` v22+
### What changes were proposed in this pull request?

This PR aims to use `int64_t` instead of `google::protobuf::int64` to follow ProtocolBuff v22.0 changes.

- https://github.com/protocolbuffers/protobuf/releases/tag/v22.0

> Fixed C++ code generation for protos that use int32_t, uint32_t, int64_t, uint64_t, size_t as field names.

### Why are the changes needed?

Currently, `branch-2.1` branch CIs are broken like the following.
- https://github.com/apache/orc/pull/2384
  - https://github.com/apache/orc/actions/runs/17682608443/job/50260045180?pr=2384

```
In file included from /Users/runner/work/orc/orc/c++/src/io/InputStream.cc:19:
/Users/runner/work/orc/orc/c++/src/io/InputStream.hh:75:31: error: no type named 'int64' in namespace 'google::protobuf'
    virtual google::protobuf::int64 ByteCount() const override;
            ~~~~~~~~~~~~~~~~~~^
/Users/runner/work/orc/orc/c++/src/io/InputStream.cc:115:21: error: no type named 'int64' in namespace 'google::protobuf'
  google::protobuf::int64 SeekableArrayInputStream::ByteCount() const {
  ~~~~~~~~~~~~~~~~~~^
/Users/runner/work/orc/orc/c++/src/io/InputStream.cc:116:42: error: no type named 'int64' in namespace 'google::protobuf'
    return static_cast<google::protobuf::int64>(position_);
                       ~~~~~~~~~~~~~~~~~~^
3 errors generated.
```

### How was this patch tested?

Pass the CIs.

### Was this patch authored or co-authored using generative AI tooling?

No.

Closes #2386 from dongjoon-hyun/ORC-1973-2.1.

Authored-by: Dongjoon Hyun <dongjoon@apache.org>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>