ORC-1042: Ignore unused-function C++ compile warning on CentOS 7 (#956)
### What changes were proposed in this pull request?

This PR aims to recover C++ compilation on CentOS 7.

### Why are the changes needed?

Since https://github.com/apache/orc/pull/951/files, it's broken.
```
Started apache/main on centos7 at Mon Nov  1 10:20:20 AM PDT 2021
Cloning into 'orc'...
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
...
[ 39%] Building CXX object c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o
In file included from /root/orc/c++/src/io/InputStream.hh:22:0,
                 from /root/orc/c++/src/io/InputStream.cc:20:
/root/orc/build/c++/src/Adaptor.hh:188:15: error: 'bool orc::multiplyExact(int64_t, int64_t, int64_t*)' defined but not used [-Werror=unused-function]
   static bool multiplyExact(int64_t value, int64_t repetitions, int64_t* result) {
               ^
/root/orc/build/c++/src/Adaptor.hh:200:15: error: 'bool orc::addExact(int64_t, int64_t, int64_t*)' defined but not used [-Werror=unused-function]
   static bool addExact(int64_t sum, int64_t increment, int64_t* result) {
               ^
cc1plus: all warnings being treated as errors
make[2]: *** [c++/src/CMakeFiles/orc.dir/io/InputStream.cc.o] Error 1
make[1]: *** [c++/src/CMakeFiles/orc.dir/all] Error 2
make: *** [all] Error 2
FAILED centos7
```

### How was this patch tested?

Manual test on CentOS.

(cherry picked from commit 95541a8b71f53d828c8f2debf9fc96ab32917288)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>