ORC-2003: Upgrade `guava` to 33.5.0-jre
### What changes were proposed in this pull request?
This PR aims to upgrade `guava` to 33.5.0-jre.

### Why are the changes needed?

https://github.com/apache/orc/actions/runs/17914579352/job/50933668060?pr=2410

```
TestSerializationUtils.testSubtractionOverflowGuava:138 expected: <overflow: checkedSubtract(22222222222, -9223372036854775808)> but was: <long overflow>
```

https://github.com/google/guava/commit/fec36dc383ac3388bfcb1decb1cb94ba63eabad2

### How was this patch tested?
GA

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #2413 from cxzl25/ORC-2003.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>
(cherry picked from commit 4ff03de0213505d09edac733d277c5e9ae403d53)
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>