ORC-1698: Upgrade `commons-cli` to 1.7.0
### What changes were proposed in this pull request?
This PR aims to upgrade `commons-cli` to 1.7.0.

### Why are the changes needed?
Release 1.7.0 – 2024-04-13

https://commons.apache.org/proper/commons-cli/changes-report.html#a1.7.0

The default value of `getOptionValue` is null. After upgrading to 1.7.0, a new method was introduced, causing compilation to fail.

```java
this.bloomFilterColumns = opts.getOptionValue('b', null);
```

```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project orc-tools: Compilation failure
Error:  /root/orc/java/tools/src/java/org/apache/orc/tools/convert/ConvertTool.java:[202,35] reference to getOptionValue is ambiguous
Error:    both method getOptionValue(char,java.lang.String) in org.apache.commons.cli.CommandLine and method getOptionValue(char,java.util.function.Supplier<java.lang.String>) in org.apache.commons.cli.CommandLine match
```

### How was this patch tested?
GA

### Was this patch authored or co-authored using generative AI tooling?
No

Closes #1906

Closes #1907 from cxzl25/ORC-1698.

Authored-by: sychen <sychen@ctrip.com>
Signed-off-by: Dongjoon Hyun <dongjoon@apache.org>